"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { Provider } from "react-redux";
import store from "@/store/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <Provider store={store}>
        <html lang="en">
          <SessionProvider session={session}>
            <body className={inter.className}>{children}</body>
          </SessionProvider>
        </html>
    </Provider>
  );
}
